const data = [
  {
    "id": 1,
    "Employees": "John Doe",
    "Designation": "Software Engineer",
    "Mail": "john.doe@example.com",
    "Location": "New York",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.5,
    "Software": "React",
    "CurrentSalary": 80000,
    "Address": "123 Main St, New York"
  },
  {
    "id": 2,
    "Employees": "Jane Smith",
    "Designation": "UI/UX Designer",
    "Mail": "jane.smith@example.com",
    "Location": "San Francisco",
    "Status": "Active",
    "Trustworthiness": "Medium",
    "Rating": 4.2,
    "Software": "Figma",
    "CurrentSalary": 75000,
    "Address": "456 Oak St, San Francisco"
  },
  {
    "id": 3,
    "Employees": "Bob Johnson",
    "Designation": "Database Administrator",
    "Mail": "bob.johnson@example.com",
    "Location": "Chicago",
    "Status": "Inactive",
    "Trustworthiness": "Low",
    "Rating": 3.8,
    "Software": "MySQL",
    "CurrentSalary": 70000,
    "Address": "789 Elm St, Chicago"
  },
  {
    "id": 4,
    "Employees": "Alice Williams",
    "Designation": "Network Engineer",
    "Mail": "alice.williams@example.com",
    "Location": "Los Angeles",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.7,
    "Software": "Cisco",
    "CurrentSalary": 85000,
    "Address": "101 Pine St, Los Angeles"
  },
  {
    "id": 5,
    "Employees": "Chris Brown",
    "Designation": "Frontend Developer",
    "Mail": "chris.brown@example.com",
    "Location": "Seattle",
    "Status": "Active",
    "Trustworthiness": "Medium",
    "Rating": 4.0,
    "Software": "Angular",
    "CurrentSalary": 78000,
    "Address": "222 Cedar St, Seattle"
  },
  {
    "id": 6,
    "Employees": "Eva White",
    "Designation": "System Analyst",
    "Mail": "eva.white@example.com",
    "Location": "Austin",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.8,
    "Software": "Java",
    "CurrentSalary": 82000,
    "Address": "333 Oak St, Austin"
  },
  {
    "id": 7,
    "Employees": "David Lee",
    "Designation": "DevOps Engineer",
    "Mail": "david.lee@example.com",
    "Location": "Denver",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.6,
    "Software": "Docker",
    "CurrentSalary": 81000,
    "Address": "444 Maple St, Denver"
  },
  {
    "id": 8,
    "Employees": "Sophia Turner",
    "Designation": "Mobile App Developer",
    "Mail": "sophia.turner@example.com",
    "Location": "Miami",
    "Status": "Active",
    "Trustworthiness": "Medium",
    "Rating": 4.3,
    "Software": "Swift",
    "CurrentSalary": 76000,
    "Address": "555 Elm St, Miami"
  },
  {
    "id": 9,
    "Employees": "Kevin Adams",
    "Designation": "Data Scientist",
    "Mail": "kevin.adams@example.com",
    "Location": "Atlanta",
    "Status": "Inactive",
    "Trustworthiness": "Low",
    "Rating": 3.5,
    "Software": "Python",
    "CurrentSalary": 69000,
    "Address": "666 Cedar St, Atlanta"
  },
  {
    "id": 10,
    "Employees": "Lily Baker",
    "Designation": "Graphic Designer",
    "Mail": "lily.baker@example.com",
    "Location": "Portland",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.9,
    "Software": "Photoshop",
    "CurrentSalary": 90000,
    "Address": "777 Maple St, Portland"
  },
  {
    "id": 11,
    "Employees": "Michael Wright",
    "Designation": "Quality Assurance Engineer",
    "Mail": "michael.wright@example.com",
    "Location": "Houston",
    "Status": "Active",
    "Trustworthiness": "Medium",
    "Rating": 4.1,
    "Software": "Selenium",
    "CurrentSalary": 73000,
    "Address": "888 Oak St, Houston"
  },
  {
    "id": 12,
    "Employees": "Olivia Taylor",
    "Designation": "Business Analyst",
    "Mail": "olivia.taylor@example.com",
    "Location": "Phoenix",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.7,
    "Software": "Excel",
    "CurrentSalary": 82000,
    "Address": "999 Cedar St, Phoenix"
  },
  {
    "id": 13,
    "Employees": "Daniel Moore",
    "Designation": "Cybersecurity Analyst",
    "Mail": "daniel.moore@example.com",
    "Location": "Detroit",
    "Status": "Inactive",
    "Trustworthiness": "Low",
    "Rating": 3.6,
    "Software": "Wireshark",
    "CurrentSalary": 71000,
    "Address": "111 Pine St, Detroit"
  },
  {
    "id": 14,
    "Employees": "Grace Clark",
    "Designation": "Project Manager",
    "Mail": "grace.clark@example.com",
    "Location": "Dallas",
    "Status": "Active",
    "Trustworthiness": "Medium",
    "Rating": 4.2,
    "Software": "Jira",
    "CurrentSalary": 78000,
    "Address": "222 Cedar St, Dallas"
  },
  {
    "id": 15,
    "Employees": "Samuel Turner",
    "Designation": "IT Support Specialist",
    "Mail": "samuel.turner@example.com",
    "Location": "Minneapolis",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.8,
    "Software": "Help Desk",
    "CurrentSalary": 75000,
    "Address": "263 Cedar St, Dallas"
  },
  {
    "id": 16,
    "Employees": "Isabella Rodriguez",
    "Designation": "Full Stack Developer",
    "Mail": "isabella.rodriguez@example.com",
    "Location": "Raleigh",
    "Status": "Active",
    "Trustworthiness": "Medium",
    "Rating": 4.4,
    "Software": "Node.js",
    "CurrentSalary": 82000,
    "Address": "333 Elm St, Raleigh"
  },
  {
    "id": 17,
    "Employees": "Christopher Garcia",
    "Designation": "Cloud Solutions Architect",
    "Mail": "christopher.garcia@example.com",
    "Location": "Las Vegas",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.9,
    "Software": "AWS",
    "CurrentSalary": 90000,
    "Address": "444 Oak St, Las Vegas"
  },
  {
    "id": 18,
    "Employees": "Aiden Martinez",
    "Designation": "Mobile App Developer",
    "Mail": "aiden.martinez@example.com",
    "Location": "Orlando",
    "Status": "Active",
    "Trustworthiness": "Medium",
    "Rating": 4.2,
    "Software": "Flutter",
    "CurrentSalary": 78000,
    "Address": "555 Cedar St, Orlando"
  },
  {
    "id": 19,
    "Employees": "Victoria Turner",
    "Designation": "Network Administrator",
    "Mail": "victoria.turner@example.com",
    "Location": "Philadelphia",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.7,
    "Software": "Cisco",
    "CurrentSalary": 85000,
    "Address": "666 Oak St, Philadelphia"
  },
  {
    "id": 20,
    "Employees": "Leo Wright",
    "Designation": "Data Analyst",
    "Mail": "leo.wright@example.com",
    "Location": "Nashville",
    "Status": "Inactive",
    "Trustworthiness": "Low",
    "Rating": 3.5,
    "Software": "R",
    "CurrentSalary": 69000,
    "Address": "777 Elm St, Nashville"
  },
  {
    "id": 21,
    "Employees": "Zoe Adams",
    "Designation": "UI/UX Designer",
    "Mail": "zoe.adams@example.com",
    "Location": "Charlotte",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.6,
    "Software": "Sketch",
    "CurrentSalary": 81000,
    "Address": "888 Cedar St, Charlotte"
  },
  {
    "id": 22,
    "Employees": "Mason White",
    "Designation": "Software Engineer",
    "Mail": "mason.white@example.com",
    "Location": "San Diego",
    "Status": "Active",
    "Trustworthiness": "Medium",
    "Rating": 4.0,
    "Software": "Java",
    "CurrentSalary": 76000,
    "Address": "999 Oak St, San Diego"
  },
  {
    "id": 23,
    "Employees": "Sofia Baker",
    "Designation": "Business Intelligence Analyst",
    "Mail": "sofia.baker@example.com",
    "Location": "Tampa",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.8,
    "Software": "Tableau",
    "CurrentSalary": 83000,
    "Address": "111 Cedar St, Tampa"
  },
  {
    "id": 24,
    "Employees": "Connor Adams",
    "Designation": "Quality Assurance Tester",
    "Mail": "connor.adams@example.com",
    "Location": "Kansas City",
    "Status": "Active",
    "Trustworthiness": "Medium",
    "Rating": 4.3,
    "Software": "Selenium",
    "CurrentSalary": 77000,
    "Address": "222 Pine St, Kansas City"
  },
  {
    "id": 25,
    "Employees": "Scarlett Clark",
    "Designation": "Frontend Developer",
    "Mail": "scarlett.clark@example.com",
    "Location": "Indianapolis",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.9,
    "Software": "React",
    "CurrentSalary": 88000,
    "Address": "333 Cedar St, Indianapolis"
  },
  {
    "id": 26,
    "Employees": "James Martin",
    "Designation": "Cybersecurity Analyst",
    "Mail": "james.martin@example.com",
    "Location": "Columbus",
    "Status": "Inactive",
    "Trustworthiness": "Low",
    "Rating": 3.7,
    "Software": "Firewall",
    "CurrentSalary": 72000,
    "Address": "444 Oak St, Columbus"
  },
  {
    "id": 27,
    "Employees": "Madison Taylor",
    "Designation": "IT Support Specialist",
    "Mail": "madison.taylor@example.com",
    "Location": "Albuquerque",
    "Status": "Active",
    "Trustworthiness": "Medium",
    "Rating": 4.2,
    "Software": "Help Desk",
    "CurrentSalary": 75000,
    "Address": "555 Elm St, Albuquerque"
  },
  {
    "id": 28,
    "Employees": "Logan Rodriguez",
    "Designation": "DevOps Engineer",
    "Mail": "logan.rodriguez@example.com",
    "Location": "Louisville",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.5,
    "Software": "Jenkins",
    "CurrentSalary": 80000,
    "Address": "666 Cedar St, Louisville"
  },
  {
    "id": 29,
    "Employees": "Abigail Turner",
    "Designation": "Database Administrator",
    "Mail": "abigail.turner@example.com",
    "Location": "Oklahoma City",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.8,
    "Software": "SQL Server",
    "CurrentSalary": 83000,
    "Address": "777 Pine St, Oklahoma City"
  },
  {
    "id": 30,
    "Employees": "Ethan Moore",
    "Designation": "System Analyst",
    "Mail": "ethan.moore@example.com",
    "Location": "Salt Lake City",
    "Status": "Active",
    "Trustworthiness": "High",
    "Rating": 4.8,
    "Software": "SQL Server",
    "CurrentSalary": 83000,
    "Address": "777 Pine St, Oklahoma City"
  }
]

export default data 
